SELECT * FROM SAWON 
WHERE DEPTNO IN ( SELECT DEPTNO FROM SAWON WHERE SANAME='최불암');

SELECT * FROM SAWON 
WHERE SAJOB IN ( SELECT SAJOB FROM SAWON WHERE SANAME='전도현');


SELECT * FROM GOGEK 
WHERE SUBSTR(GOADDR,1,2) = (SELECT SUBSTR(GOADDR,1,2) FROM GOGEK WHERE GONAME='류민');

/* 연습문제.
[사원테이블]전도현과 동일한 연봉을 받는 직원 추출.
[사원테이블]최불암과 같은 달에 입사한 직원 추출.
[사원테이블]이미자와 같은 계절에 입사한 직원 추출.
[고객테이블]마징가와 동일한 연대에 출생한 고객 추출.
[고객테이블]짱가와 동일한 월에 태어난 고객 추출.
*/

SELECT * FROM SAWON WHERE SAPAY =(SELECT SAPAY FROM SAWON WHERE SANAME='전도현');
SELECT * FROM SAWON WHERE TO_NUMBER(TO_CHAR(SAHIRE, 'MM'))=(SELECT TO_NUMBER(TO_CHAR(SAHIRE, 'MM')) FROM SAWON WHERE SANAME='최불암');
SELECT * FROM SAWON WHERE FLOOR(TO_NUMBER(TO_CHAR(SAHIRE, 'MM'))/3) = (SELECT FLOOR(TO_NUMBER(TO_CHAR(SAHIRE, 'MM'))/3) FROM SAWON WHERE SANAME='이미자');
SELECT * FROM GOGEK WHERE TO_NUMBER(SUBSTR(GOJUMIN,1,1))=(SELECT TO_NUMBER(SUBSTR(GOJUMIN,1,1)) FROM GOGEK WHERE GONAME='마징가');
SELECT * FROM GOGEK WHERE SUBSTR(GOJUMIN,3,2)=(SELECT SUBSTR(GOJUMIN,3,2) FROM GOGEK WHERE GONAME='짱가');