SELECT
	COUNT(*) AS 전체사원수,
	COUNT(SAMGR) AS 부서장제외직원수,
	SUM(SAPAY) AS 전체급여합계,
	AVG(SAPAY) AS 전체급여평균,
	MIN(SAPAY) AS 최저급여,
	MAX(SAPAY) AS 최대급여,
	MIN(SAHIRE) AS 가장최근입사일자,
	MAX(SAHIRE) AS 가장최초입사일자
FROM SAWON;



SELECT * FROM SAWON
WHERE SAPAY > (SELECT AVG(SAPAY) FROM SAWON);


SELECT MAX(SAPAY) FROM SAWON WHERE DEPTNO=10;

SELECT * FROM SAWON WHERE SAPAY = (SELECT MAX(SAPAY) FROM SAWON WHERE DEPTNO=10) AND DEPTNO=10;

SELECT * FROM SAWON S
WHERE SAPAY=(SELECT MAX(SAPAY) FROM SAWON WHERE DEPTNO=S.DEPTNO);