SELECT * FROM SAWON ORDER BY DEPTNO, SASEX;

SELECT 
	DEPTNO, COUNT(*) AS 인원수, 
	SUM(SAPAY) AS 급여합계, 
	FLOOR(AVG(SAPAY)) AS 급여평균,
	MIN(SAPAY) AS 최저급여,
	MAX(SAPAY) AS 최고급여
FROM SAWON
GROUP BY DEPTNO
ORDER BY DEPTNO;


SELECT DEPTNO AS 부서명, SASEX, COUNT(SASEX) AS 부서별성별인원수
FROM SAWON
GROUP BY DEPTNO, SASEX
ORDER BY DEPTNO;


SELECT COUNT(*) AS 입사월별_인원수, TO_CHAR(SAHIRE, 'MM') AS 입사월
FROM SAWON
GROUP BY TO_CHAR(SAHIRE, 'MM')
ORDER BY COUNT(*) DESC;


SELECT SUBSTR(GOADDR,1,2) AS 지역, COUNT(*) AS 지역별_인원수
FROM GOGEK
GROUP BY SUBSTR(GOADDR,1,2);


SELECT
	CASE WHEN MOD(SUBSTR(GOJUMIN, 8, 1),2)=1 THEN '남자' ELSE '여자' END AS 성별,
	COUNT(CASE WHEN MOD(SUBSTR(GOJUMIN, 8, 1),2)=1 THEN '남자' ELSE '여자' END) AS 성별인원수
FROM GOGEK
GROUP BY 
	CASE WHEN MOD(SUBSTR(GOJUMIN, 8, 1),2)=1 THEN '남자' ELSE '여자' END;
	
	
SELECT DEPTNO AS 부서명, COUNT(DEPTNO) AS 부서별_인원수
FROM SAWON
GROUP BY DEPTNO;

SELECT DEPTNO AS 부서명, SAJOB AS 직급, COUNT(SAJOB) AS 직급별_인원수
FROM SAWON
GROUP BY DEPTNO, SAJOB
ORDER BY DEPTNO ;

SELECT TO_CHAR(SAHIRE, 'YYYY') AS 입사년도, COUNT(TO_CHAR(SAHIRE, 'YYYY')) AS 입사년도별_인원수
FROM SAWON
GROUP BY TO_CHAR(SAHIRE, 'YYYY')
ORDER BY TO_CHAR(SAHIRE, 'YYYY');

SELECT SUBSTR(TO_CHAR(SAHIRE, 'YYYY'),1,3)||'0년대' AS 입사년대, COUNT(SUBSTR(TO_CHAR(SAHIRE, 'YYYY'),1,3)) AS 입사년대별_인원수 
FROM SAWON
GROUP BY SUBSTR(TO_CHAR(SAHIRE, 'YYYY'),1,3)
ORDER BY SUBSTR(TO_CHAR(SAHIRE, 'YYYY'),1,3);

SELECT 
	CASE FLOOR(TO_NUMBER(SUBSTR(GOJUMIN,3,2))/3)
		WHEN 1 THEN '봄'
		WHEN 2 THEN '여름'
		WHEN 3 THEN '가을'
		ELSE '겨울'
	END AS 계절,
	COUNT(
		CASE FLOOR(TO_NUMBER(SUBSTR(GOJUMIN,3,2))/3)
			WHEN 1 THEN '봄'
			WHEN 2 THEN '여름'
			WHEN 3 THEN '봄'
			ELSE '겨울'
		END) AS 계절별_입사_인원수
FROM GOGEK
GROUP BY
	CASE FLOOR(TO_NUMBER(SUBSTR(GOJUMIN,3,2))/3)
		WHEN 1 THEN '봄'
		WHEN 2 THEN '여름'
		WHEN 3 THEN '가을'
		ELSE '겨울'
	END;
	

SELECT DEPTNO, COUNT(*)
FROM SAWON
GROUP BY DEPTNO
HAVING COUNT(*) >= 5;