CREATE OR REPLACE VIEW SAWON_MAN_VIEW
 AS SELECT *
 FROM SAWON
 WHERE SASEX='남자';
 
 SELECT * FROM SAWON_MAN_VIEW;
 

CREATE OR REPLACE VIEW GOGEK_VIEW
AS 
	select
		GOBUN, GONAME, GOADDR, GOJUMIN, GODAM,
		CASE FLOOR(TO_NUMBER(SUBSTR(GOJUMIN,3,2))/3)
			WHEN 1 THEN '봄'
			WHEN 2 THEN '여름'
			WHEN 3 THEN '가을'
			ELSE '겨울'
		END AS GOSEASON
	FROM GOGEK;
	
SELECT * FROM GOGEK_VIEW;

SELECT GOSEASON, COUNT(*) AS 계절별_고객수
FROM GOGEK_VIEW
GROUP BY GOSEASON
ORDER BY COUNT(*);
	

CREATE OR REPLACE VIEW T_GOGEK_VIEW_1
AS
	SELECT
			GOBUN, GONAME, GOADDR, 
			RPAD(SUBSTR(GOJUMIN,1,8),14,'*') AS GOJUMIN,
			CASE SUBSTR(GOJUMIN,1,1)
				WHEN '0' THEN '20'||SUBSTR(GOJUMIN,1,2)
				ELSE '19'||SUBSTR(GOJUMIN,1,2)
			END AS BIRTH_YEAR
	FROM GOGEK;

SELECT * FROM T_GOGEK_VIEW_1;

CREATE OR REPLACE VIEW T_GOGEK_VIEW_2
AS
	SELECT
		TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY'))-BIRTH_YEAR+1 AS AGE,
		CASE MOD(BIRTH_YEAR, 12)
			WHEN 0 THEN '원숭이'
			WHEN 1 THEN '닭'
			WHEN 2 THEN '개'
			WHEN 3 THEN '돼지'
			WHEN 4 THEN '쥐'
			WHEN 5 THEN '소'
			WHEN 6 THEN '호랑이'
			WHEN 7 THEN '토끼'
			WHEN 8 THEN '용'
			WHEN 9 THEN '뱀'
			WHEN 10 THEN '말'
			WHEN 11 THEN '양'
		END AS TII
	FROM T_GOGEK_VIEW_1
	ORDER BY AGE;
	
SELECT * FROM T_GOGEK_VIEW_2;

-- [system 계정으로 전환] 추가 계정 생성

CREATE USER TEST1 IDENTIFIED BY TEST1;
GRANT CONNECT TO TEST1;

-- [test 계정으로 전환]
grant select on t_gogek_view_2 to test1;

SELECT * FROM TEST.T_GOGEK_VIEW_2;