ALTER TABLE SAWON ADD CONSTRAINT FK_SAWON_DEPTNO FOREIGN KEY(DEPTNO) REFERENCES	DEPT(DEPTNO);
ALTER TABLE SAWON ADD CONSTRAINT FK_SAWON_SAMGR FOREIGN KEY(SAMGR) REFERENCES	SAWON(SABUN);
ALTER TABLE GOGEK ADD CONSTRAINT FK_GOGEK_GODAM FOREIGN KEY(GODAM) REFERENCES	SAWON(SABUN);


select * from sawon,dept;
select * from sawon cross join dept;

select * from sawon s, dept d where s.deptno = d.deptno;
select * from sawon s inner join dept d on s.deptno=d.deptno
where sapay > 3000;

SELECT * FROM SAWON S, GOGEK G WHERE S.SABUN = G.GODAM
ORDER BY S.SABUN;

SELECT * FROM SAWON S, GOGEK G WHERE S.SABUN=G.GODAM(+) ORDER BY SABUN;
SELECT * FROM SAWON S LEFT OUTER JOIN GOGEK G ON S.SABUN=G.GODAM ORDER BY SABUN;

SELECT * FROM SAWON S1, SAWON S2 WHERE S1.SAMGR = S2.SABUN(+);
SELECT * FROM SAWON S1 LEFT OUTER JOIN SAWON S2 ON S1.SAMGR = S2.SABUN;
SELECT * FROM SAWON S1 FULL OUTER JOIN SAWON S2 ON S1.SAMGR = S2.SABUN;

SELECT SABUN,SANAME,DNAME,GONAME
FROM (SAWON S INNER JOIN DEPT D ON S.DEPTNO=D.DEPTNO)
	LEFT OUTER JOIN GOGEK G ON S.SABUN=G.GODAM
ORDER BY SABUN;


SELECT S1.SABUN, S2.SAJOB, S1.SANAME, DNAME, S2.SAJOB, S2.SANAME
FROM (SAWON S1 INNER JOIN DEPT D ON S1.DEPTNO=D.DEPTNO) LEFT OUTER JOIN SAWON S2 ON S1.SAMGR=S2.SABUN;


-- 상사
SELECT S2.SAJOB, S2.SANAME, G2.GONAME, S2.SAMGR
FROM (SAWON S1 INNER JOIN SAWON S2 ON S1.SAMGR=S2.SABUN) INNER JOIN GOGEK G2 ON S2.SABUN=G2.GODAM;

-- 사원
SELECT S1.SABUN, S1.SANAME, G1.GONAME, S1.SAMGR
FROM SAWON S1 INNER JOIN GOGEK G1 ON S1.SABUN=G1.GODAM;

SELECT *
FROM ((SAWON S1 LEFT OUTER JOIN GOGEK G1 ON S1.SABUN=G1.GODAM) INNER JOIN DEPT D ON S1.DEPTNO=D.DEPTNO)
	LEFT OUTER JOIN SAWON S2 ON S1.SAMGR=S2.SABUN
	LEFT OUTER JOIN GOGEK G2 ON S2.SABUN=G2.GODAM;