

CREATE SEQUENCE SEQ_TEST

SELECT 
	SEQ_TEST.NEXTVAL,
	SEQ_TEST.CURRVAL
FROM DUAL;


CREATE TABLE TB10
(
	IDX INT,
	CONSTRAINT PK_TB10_IDX PRIMARY KEY(IDX)
)


CREATE SEQUENCE SEQ_TB10_IDX

INSERT INTO TB10 VALUES(SEQ_TB10_IDX.NEXTVAL);
INSERT INTO TB10 VALUES(SEQ_TB10_IDX.NEXTVAL);
INSERT INTO TB10 VALUES(SEQ_TB10_IDX.NEXTVAL);
INSERT INTO TB10 VALUES(SEQ_TB10_IDX.NEXTVAL);
INSERT INTO TB10 VALUES(SEQ_TB10_IDX.NEXTVAL);

SELECT * FROM TB10;